version: "3.8"

services:

  accounts:
    image: frisson123/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tj-network
    
  loans:
    image: frisson123/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tj-network
    
  cards:
    image: frisson123/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tj-network
    
networks:
  tj-network: